server:
  port: 7600
spring:
  application:
    name: jxmall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.10:8848

  thymeleaf:
    cache: false

  redis:
    host: 192.168.79.10
    port: 6379
    password: li15854198694

  session:
    store-type: redis

