server:
  port: 7700

spring:
  application:
    name: jxmall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.10:8848

    # 配置sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

  thymeleaf:
    cache: false

  session:
    store-type: redis

  redis:
    host: 192.168.79.10
    port: 6379
    password: li15854198694

  # 服务追踪
  zipkin:
    base-url: http://192.168.79.10:9411/
    # 关闭服务发现，否则SpringCloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    # 设置使用 http 的方式传输数据
    sender:
      type: web
  # 设置抽样采集率为 100%，默认为 0.1，即 10%
  sleuth:
    sampler:
      probability: 1

# 开启feign的sentinel功能
feign:
  sentinel:
    enabled: true
