server:
  port: 7200

spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    # 商品数据库 pms
    url: jdbc:mysql://192.168.79.10:3306/jxmall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: lee
    password: li15854198694

  application:
    name: jxmall-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.10:8848

  # redis
  redis:
    host: 192.168.79.10
    port: 6379
    password: li15854198694

  session:
    store-type: redis

  # rabbitmq
  rabbitmq:
    host: 192.168.79.10
    port: 5672
    virtual-host: /
    username: root
    password: 123
    # 开启发送端确认
    publisher-returns: true
    # 开启发送端消息抵达Broker确认
    publisher-confirm-type: correlated
    # 只要消息抵达Queue，就会异步发送优先回调returnfirm
    template:
      mandatory: true
    #消息确认机制 --- 是否开启手ack动确认模式   manual 开启
    listener:
      simple:
        acknowledge-mode: manual

  thymeleaf:
    cache: false

  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss

# 自定义线程池配置
jxmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

mybatis-plus:
  # sql映射文件
  mapper-locations: classpath:/mapper/**/*.xml
  # 设置主键自增
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.lee: debug

# 支付宝相关配置
alipay:
  app-id: 2021000118600840
  merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCaAx341SmTOzxwtdBumvUYBSAzLOB7dD6L9jjLKLViiXgU4aPebO4+iNK8326TG79MAsSoGjjHPcRWbh0ILQH3GMvHGH8Ndp9sXANg/bdQblle4AQGas0d16SuKHORE0JeLw7obankZi5HbR1emT1vhYC4t0K1K4choYcZIMyS2QVDPsekc7Ap1sk94bFZ4badTcHVjIM/xW7+yZtEORYu8LeFeZ3N4OM+LoFzLGx/jRsGeEhAruJkpgS7AojjVAcYsCxi0RUJcZVG3EjBVJ6y8+r6vtMs8eCIZ/RmfLxfLjdftozfoMLPffw0Bnt19Y4ujZq5W5VpIkciBN9Khz7hAgMBAAECggEBAIDAgln3uh3/s3N2S51rpeJCxryBk9khQPi5CpmsmpaZ3e13BQt5fWKB98s17rbEx5O/7K+r3DOUi4LF4zdmiPINpK346J5UwMpR0fFPqeRvm/8Yv8StnHSKRn3iC1sJAr7CEHB23US3t5C2w4rGCPomXYoOipHypbGT2+FB7kQEJTcHFmIMJsMlLh8UIgt4yN4DQcEh0TKkFVlGc9cXmu+45SCEWonAlcrElYMg9mz7XJWdMLs+RpbSrY+/jGKeuO+gh3B4ztTXxxkO8qbDlaV2t3N7b4EBFmrKlQWqLcTwQoTpL1/4vTlOj37KbRbQrKYBODDev9ViVN3f4h8KbxECgYEA0nel2Zu9XlRDY9gyve39ncI/lSfC+f8T7YGNag3kL2sNtK84SXt1iCubrq/NXEl4lqp6NP18g80ZtigrHCwuLQyhKn/0OKCNwlrRZ9/LSpJS+zqNcZW6qw4hUTmidCyzelGAcv7KwLJms3R7sTF1FdH0aKuaaOmlVYJ5GiRmCz8CgYEAu1TNCBU5CQoFU2W10tii3ds0Tb1zn/8fQT6a6LltbqVw8NAeLW+6z128CK+RG8V7XKzpsSMETuffa6m2kQ7KXXwGYHkE0u0S3hOBtlWEfGZlxxbYkevqv/kHQn1RXC5gdmtwhoAdEBphws7IzgmGo/QXt9Qeb0vWPDcG2GLezd8CgYEAjLpeFiQxuhojuWY9f4vbshnJhAVDNQAfJgcjNI+3TRGK547l1xSLIRLvlR2N9jBWRoAVGMuJ72M71vYC5WKROaQhO5a1CQwp3ZP2Qzt75g/zFnMvUoyodWoMUxBzlLSzCY3nknzVu4VOcJ3pezCztnRdtYNQyue3mnaUXSuLY+cCgYBqqgpkg9EJ+I63wb4Z5Ag4UswhR7JCc72UJNWHla1dxw3b0GSecnPoBvM97tms+nEXf81AczPMyfJJF0VAqy9Gs4vd+opon1yS3oCJFYBuZM+m4LdHvxDXZjBgB4L//dgnFV3o96GUvbDUf3GO/5WOXTn0De+WZ5QAjUR0iTdb+QKBgDYEd8yRZacBiCzM+oxg29ajZ68T7MwWgzcc+PX/KENIYKSvVHaD4a4FJPHA6xn2Fqz/d3Gfrp5nAob3IIteOO69ouDOSckQ0xgBTMvvEAMCy5Wm3bIosT77/A4VMmtUXY8V4GoIpkTPJ+EKXB58NUyA4h95tAmkDu0L9+172+zE
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhcUzAUD+1UgVFQjAdVQynx1AWOrkjK4ln/wSTzZH+LpSaDXt5c3LyA7+U1RCeUXot69ZgTGLKWdLJPoyb33CUIfOnn7TRK20tYAcUWyBzEDm69PSJigSaqsRKYTmoAQMHf3Xk4acx6HuP/z2EQ9W6nExX/OCFyAnHYGjbUQLb/7pPYW1qWWNnF7Zg3Vh3n5yVMbs4amUSUMWgBJc4hAF+0v9WoYMyLYAMSp3rAq2M69LBhMmemViNwlD2RALTInravG6JUnrx3i0FuZH2IeXPZg9mV680ao5ibckV1WxMg2JjlgTn80xB3B9pGBJLyfi5PZfbxLN5f4HcFwwK3JESwIDAQAB
  notify_url: http://remsph.natappfree.cc/payed/notify
  return-url: http://member.gulimall.com/memberOrder.html
  sign-type: RSA2
  charset: utf-8
  gateway-url: https://openapi.alipaydev.com/gateway.do
