server:
  port: 7900

spring:
  application:
    name: jxmall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.10:8848

  session:
    store-type: redis

  redis:
    host: 192.168.79.10
    port: 6379
    password: li15854198694

  thymeleaf:
    cache: false

  # rabbitmq
  rabbitmq:
    host: 192.168.79.10
    port: 5672
    virtual-host: /
    username: root
    password: 123
    # 开启发送端确认
    publisher-returns: true
    # 开启发送端消息抵达Broker确认
    publisher-confirm-type: correlated
    # 只要消息抵达Queue，就会异步发送优先回调returnfirm
    template:
      mandatory: true
    #消息确认机制 --- 是否开启手ack动确认模式   manual 开启
    listener:
      simple:
        acknowledge-mode: manual
