server:
  port: 7900

spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    # 商品数据库 pms
    url: jdbc:mysql://192.168.79.10:3306/jxmall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: lee
    password: li15854198694

  application:
    name: jxmall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.10:8848

    # 配置sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

  session:
    store-type: redis

  redis:
    host: 192.168.79.10
    port: 6379
    password: li15854198694

  thymeleaf:
    cache: false

  # rabbitmq
  rabbitmq:
    host: 192.168.79.10
    port: 5672
    virtual-host: /
    username: root
    password: 123
    # 开启发送端确认
    publisher-returns: true
    # 开启发送端消息抵达Broker确认
    publisher-confirm-type: correlated
    # 只要消息抵达Queue，就会异步发送优先回调returnfirm
    template:
      mandatory: true
    #消息确认机制 --- 是否开启手ack动确认模式   manual 开启
    listener:
      simple:
        acknowledge-mode: manual

  # 服务追踪
  zipkin:
    base-url: http://192.168.79.10:9411/
    # 关闭服务发现，否则SpringCloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    # 设置使用 http 的方式传输数据
    sender:
      type: web
  # 设置抽样采集率为 100%，默认为 0.1，即 10%
  sleuth:
    sampler:
      probability: 1

# 开启feign的sentinel功能
feign:
  sentinel:
    enabled: true

logging:
  level:
    com.lee: error
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
