server:
  port: 7300

spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    # 商品数据库 pms
    url: jdbc:mysql://192.168.79.10:3306/jxmall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: lee
    password: li15854198694

  application:
    name: jxmall-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.10:8848

  # redis
  redis:
    host: 192.168.79.10
    port: 6379
    password: li15854198694

  # Cache缓存
  cache:
    # 指定缓存类型
    type: redis
    redis:
      # 指定redis中的过期时间
      time-to-live: 3600000
      # key加上前缀
      #key-prefix: CACHE_
      # 使用前缀
      # 如果指定了前缀就用指定的前缀
      # 如果没有就默认使用缓存的名字作为前缀
      use-key-prefix: true
      # 是否缓存空值，防止缓存穿透问题
      cache-null-values: true

  # 时间戳指定格式化规则
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # thymeleaf 关闭缓存
  thymeleaf:
    cache: false

  session:
    store-type: redis

mybatis-plus:
  # sql映射文件
  mapper-locations: classpath:/mapper/**/*.xml
  # 设置主键自增
  global-config:
    db-config:
      id-type: auto
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

logging:
  level:
    com.lee: error

# 自定义线程池配置
jxmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
